### ISSUE TITLE
Search doesn't work when using built files

### ISSUE THREAD

**Issue by CardboardTurkey** [not-matthias/apollo#112]
I'm finding that the search function works fine for me when I'm viewing the site via `zola serve`. However, when I run `zola build` and then serve the output with nginx, the search function no longer returns any results.

<details>

<summary>With `zola serve`</summary>

<img src="https://github.com/user-attachments/assets/2d5edb15-edb8-4c5d-8b58-45dac432632c" alt="Description" width="500">
</details>
<details>

<summary>When serving from nginx after `zola build`</summary>

<img src="https://github.com/user-attachments/assets/10bdfd78-59e0-4569-94cf-5dac2cd60e11" alt="Description" width="500">
</details>
<details>

<summary>My `config.toml`</summary>

```toml
host_url = "https://stats.mywebsite.com" # default: https://api-gateway.umami.dev/
title = "Lard will tear us apart"
description = "Italian recipes with ingredients accessible in Britain"
build_search_index = true
generate_feeds = true
compile_sass = true
minify_html = true
taxonomies = [{ name = "tags" }]
theme = "apollo"

[search]
include_title = true
include_description = true
include_path = true
include_content = true
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "ayu-light"

[extra]
toc = true
use_cdn = false
favicon = "/icon/favicon.png"
theme = "toggle"                                                       # light, dark, auto, toggle
fancy_code = true
dynamic_note = true                                                    # a note that can be toggled
mathjax = true
mathjax_dollar_inline_enable = true
repo_url = "https://github.com/not-matthias/apollo/tree/main/content/"

menu = [
    # { name = "/posts", url = "/posts", weight = 1 },
    # { name = "/projects", url = "/projects", weight = 2 },
    # { name = "/about", url = "/about", weight = 3 },
    { name = "tags", url = "/tags", weight = 4 },
]

socials = [
    { name = "gitlab", url = "https://gitlab.com/cardboardturkey/recipe-site", icon = "gitlab" },
]


stylesheets = [
    "icone.css", # at /static/icone.css
]
```
</details>

Tested with zola version 0.20.0 and 0.19.2
