### ISSUE TITLE
Bug: `base_url` in `config.toml` is not respected for `favicon` path

### ISSUE THREAD

**Issue by Kuan-Lun** [not-matthias/apollo#116]
Hi, I noticed that the `favicon` path does not seem to work correctly when a `base_url` is specified in `config.toml`.

For example, with the following config:

```toml
base_url = "https://www.example.com/apath/"
favicon = "/icon/favicon.ico"
```

The browser tries to load the favicon from `https://www.example.com/icon/favicon.ico`, ignoring the `/apath/` prefix defined in `base_url`.

To make it work, I have to manually include the base path:

```toml
favicon = "/apath/icon/favicon.ico"
```

This seems inconsistent, as I expected the `base_url` to be respected automatically.
Is this the intended behavior, or could it be a bug?

Thanks!
