### ISSUE TITLE
Bug: `local_image` resolves incorrectly when using `index.md` in subfolder

### ISSUE THREAD

**Issue by Kuan-Lun** [not-matthias/apollo#118]
Hi, thank you for the great theme!

I believe there's a bug with how `extra.local_image` is resolved when using `index.md` inside a subfolder.

# Folder structure

```
content/
├── posts/
│   └── afolder/
│       ├── index.md
│       └── image.png
└── somethings/
```

# Front matter in `index.md`

```toml
slug = "afolder"

[extra]
# local_image = "image.png"  # This results in an incorrect path
local_image = "/posts/afolder/image.png"  # This works
```

# Why I think this is a bug

In the Markdown body, using `![alt](image.png)` correctly displays the image located at `/posts/afolder/image.png`. However, the same relative path (`image.png`) does **not** work for `extra.local_image`.

To make the image appear correctly in the theme (e.g., on the post listing page), I have to hardcode the full path as `/posts/afolder/image.png`, which feels inconsistent and fragile — especially if the post's `slug` or folder changes.

# Suggestion

I think `local_image` should resolve relative to the Markdown file's directory (just like Markdown image paths do), or at least this behavior should be clarified in the documentation.

Let me know if you’d like a reproduction repo. Thanks again for your work on Apollo!
